version: '3'

services:
  docker-registry:
    container_name: docker-registry
    image: konradkleine/docker-registry-frontend:v2
    environment:
      - ENV_DOCKER_REGISTRY_HOST=hub.bloodservices.ca
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_DOCKER_REGISTRY_USE_SSL=1
    networks:
      - default
    ports:
      - '8989:80'
